import Foundation

/// Entrada individual do catálogo de URLs de Ajustes
struct SettingsURLEntry: Identifiable, Codable {
    var id = UUID()
    let name: String
    let fullPath: String
    let url: String
}

/// Categoria do catálogo de URLs
struct SettingsURLCategory: Identifiable {
    let id = UUID()
    let name: String
    let icon: String
    let entries: [SettingsURLEntry]
}

/// Atalho customizado criado pelo usuário
struct CustomShortcut: Codable, Identifiable {
    var id = UUID()
    var title: String
    var icon: String
    var shortcutName: String
    var settingsURL: String
}

/// Catálogo completo de URLs de Ajustes do iOS 26
/// Ref: https://github.com/paralevel/ios-settings-urls
enum SettingsURLCatalog {
    static let categories: [SettingsURLCategory] = [
        SettingsURLCategory(name: "Apple Account", icon: "person.crop.circle", entries: [
            SettingsURLEntry(name: "Apple Account", fullPath: "Apple Account", url: "settings-navigation://com.apple.Settings.AppleAccount"),
            SettingsURLEntry(name: "Personal Information some delay", fullPath: "Apple Account > Personal Information some delay", url: "settings-navigation://com.apple.Settings.AppleAccount/APPLE_ACCOUNT_CONTACT"),
            SettingsURLEntry(name: "Sign-In & Security some delay", fullPath: "Apple Account > Sign-In & Security some delay", url: "settings-navigation://com.apple.Settings.AppleAccount/PASSWORD_AND_SECURITY"),
            SettingsURLEntry(name: "Recovery Contacts some delay", fullPath: "Apple Account > Sign-In & Security > Recovery Contacts some delay", url: "settings-navigation://com.apple.Settings.AppleAccount/?aaaction=accountRecovery"),
            SettingsURLEntry(name: "Legacy Contact some delay", fullPath: "Apple Account > Sign-In & Security > Legacy Contact some delay", url: "settings-navigation://com.apple.Settings.AppleAccount/?aaaction=accountBeneficiary"),
            SettingsURLEntry(name: "Payment & Shipping some delay", fullPath: "Apple Account > Payment & Shipping some delay", url: "settings-navigation://com.apple.Settings.AppleAccount/PAYMENT_AND_SHIPPING"),
            SettingsURLEntry(name: "Subscriptions some delay", fullPath: "Apple Account > Subscriptions some delay", url: "settings-navigation://com.apple.Settings.AppleAccount/SUBSCRIPTIONS"),
            SettingsURLEntry(name: "iCloud see the iCloud main section for more URLs", fullPath: "Apple Account > iCloud see the iCloud main section for more URLs", url: "settings-navigation://com.apple.Settings.AppleAccount/ICLOUD_SERVICE"),
            SettingsURLEntry(name: "Family", fullPath: "Apple Account > Family", url: "settings-navigation://com.apple.Settings.AppleAccount?aaaction=showFamilySettings"),
            SettingsURLEntry(name: "Media & Purchases", fullPath: "Apple Account > Media & Purchases", url: "settings-navigation://com.apple.Settings.AppleAccount/STORE_SERVICE"),
            SettingsURLEntry(name: "Sign in with Apple", fullPath: "Apple Account > Sign in with Apple", url: "settings-navigation://com.apple.Settings.AppleAccount/SIWA_SERVICE"),
            SettingsURLEntry(name: "Contact Key Verification", fullPath: "Apple Account > Contact Key Verification", url: "settings-navigation://com.apple.Settings.AppleAccount/TRANSPARENCY"),
        ]),
        SettingsURLCategory(name: "Family", icon: "person.2", entries: [
            SettingsURLEntry(name: "Family", fullPath: "Family", url: "settings-navigation://com.apple.Settings.Family"),
            SettingsURLEntry(name: "Subscriptions", fullPath: "Family > Subscriptions", url: "settings-navigation://com.apple.Settings.Family?familyPath=/subscriptions"),
        ]),
        SettingsURLCategory(name: "Wi-Fi", icon: "wifi", entries: [
            SettingsURLEntry(name: "Wi-Fi", fullPath: "Wi-Fi", url: "settings-navigation://com.apple.Settings.WiFi"),
            SettingsURLEntry(name: "[current network] ⓘ", fullPath: "Wi-Fi > [current network] ⓘ", url: "settings-navigation://com.apple.Settings.WiFi/NetworkDetails"),
        ]),
        SettingsURLCategory(name: "Bluetooth", icon: "dot.radiowaves.left.and.right", entries: [
            SettingsURLEntry(name: "Bluetooth", fullPath: "Bluetooth", url: "settings-navigation://com.apple.Settings.Bluetooth"),
            SettingsURLEntry(name: "AirPods ⓘ use the MAC address of your AirPods as identifier – can be retrieved using a computer", fullPath: "Bluetooth > AirPods ⓘ use the MAC address of your AirPods as identifier – can be retrieved using a computer", url: "settings-navigation://com.apple.Settings.Bluetooth/HeadphoneDetail/?identifier=00:00:00:00:00:00"),
        ]),
        SettingsURLCategory(name: "Cellular", icon: "antenna.radiowaves.left.and.right", entries: [
            SettingsURLEntry(name: "Cellular", fullPath: "Cellular", url: "settings-navigation://com.apple.Settings.Cellular"),
            SettingsURLEntry(name: "Cellular Data", fullPath: "Cellular > Cellular Data (switch)", url: "settings-navigation://com.apple.Settings.Cellular#MOBILE_DATA_SETTINGS"),
            SettingsURLEntry(name: "Cellular Data Options", fullPath: "Cellular > Cellular Data Options", url: "settings-navigation://com.apple.Settings.Cellular/CELLULAR_DATA_OPTIONS"),
            SettingsURLEntry(name: "Data Mode", fullPath: "Cellular > Cellular Data Options > Data Mode", url: "settings-navigation://com.apple.Settings.Cellular/CELLULAR_DATA_OPTIONS/DATA_MODE"),
            SettingsURLEntry(name: "Network Selection", fullPath: "Cellular > Network Selection (button)", url: "settings-navigation://com.apple.Settings.Cellular#CELLULAR_NETWORK_TELEPHONY_SETTINGS"),
            SettingsURLEntry(name: "My Number", fullPath: "Cellular > My Number (button)", url: "settings-navigation://com.apple.Settings.Cellular#PHONEBOOK_TELEPHONY_SETTINGS"),
            SettingsURLEntry(name: "Wi-Fi Calling", fullPath: "Cellular > Wi-Fi Calling (button)", url: "settings-navigation://com.apple.Settings.Cellular#WIFI_CALLING_TELEPHONY_SETTINGS"),
            SettingsURLEntry(name: "Calls on Other Devices", fullPath: "Cellular > Calls on Other Devices (button)", url: "settings-navigation://com.apple.Settings.Cellular#PRIMARY_CLOUD_CALLING"),
            SettingsURLEntry(name: "SIM PIN", fullPath: "Cellular > SIM PIN (button)", url: "settings-navigation://com.apple.Settings.Cellular#SIM_PASSCODE_TELEPHONY_SETTINGS"),
            SettingsURLEntry(name: "Add eSIM", fullPath: "Cellular > Add eSIM (button)", url: "settings-navigation://com.apple.Settings.Cellular#ADD_CELLULAR_PLAN"),
            SettingsURLEntry(name: "Cellular Data Usage", fullPath: "Cellular > Cellular Data > Show All > Cellular Data Usage", url: "settings-navigation://com.apple.Settings.Cellular/SHOW_ALL"),
            SettingsURLEntry(name: "Wi-Fi Assist", fullPath: "Cellular > Wi-Fi Assist (switch)", url: "settings-navigation://com.apple.Settings.Cellular#Wi-Fi%20Assist"),
            SettingsURLEntry(name: "iCloud Drive", fullPath: "Cellular > iCloud Drive (switch)", url: "settings-navigation://com.apple.Settings.Cellular#iCloud%20Drive"),
            SettingsURLEntry(name: "iCloud Backup", fullPath: "Cellular > iCloud Backup (switch)", url: "settings-navigation://com.apple.Settings.Cellular#iCloud%20Backup"),
            SettingsURLEntry(name: "Enable Cellular Usage Statistics", fullPath: "Cellular > Enable Cellular Usage Statistics (switch)", url: "settings-navigation://com.apple.Settings.Cellular#Enable%20Cellular%20Usage%20Statistics"),
            SettingsURLEntry(name: "Reset Statistics", fullPath: "Cellular > Reset Statistics (button)", url: "settings-navigation://com.apple.Settings.Cellular#Reset%20Statistics"),
        ]),
        SettingsURLCategory(name: "Personal Hotspot", icon: "personalhotspot", entries: [
            SettingsURLEntry(name: "Personal Hotspot", fullPath: "Personal Hotspot", url: "settings-navigation://com.apple.Settings.PersonalHotspot"),
        ]),
        SettingsURLCategory(name: "Battery", icon: "battery.100percent", entries: [
            SettingsURLEntry(name: "Battery", fullPath: "Battery", url: "settings-navigation://com.apple.Settings.Battery"),
            SettingsURLEntry(name: "Battery Health & Charging device specific", fullPath: "Battery > Battery Health & Charging device specific", url: "settings-navigation://com.apple.Settings.Battery/BATTERY_HEALTH_TITLE"),
            SettingsURLEntry(name: "Charging Options device specific", fullPath: "Battery > Charging Options device specific", url: "settings-navigation://com.apple.Settings.Battery/CHARGING_OPTIONS_IDENTIFIER"),
            SettingsURLEntry(name: "Battery Percentage", fullPath: "Battery > Battery Percentage (switch)", url: "settings-navigation://com.apple.Settings.Battery#BATTERY_PERCENTAGE_IDENTIFIER"),
            SettingsURLEntry(name: "Low Power Mode", fullPath: "Battery > Low Power Mode (switch)", url: "settings-navigation://com.apple.Settings.Battery#LOW_POWER_MODE_IDENTIFIER"),
        ]),
        SettingsURLCategory(name: "VPN", icon: "lock.shield", entries: [
            SettingsURLEntry(name: "VPN", fullPath: "VPN (switch)", url: "settings-navigation://com.apple.Settings#com.apple.Settings.VPN"),
        ]),
        SettingsURLCategory(name: "General", icon: "gear", entries: [
            SettingsURLEntry(name: "General", fullPath: "General", url: "settings-navigation://com.apple.Settings.General"),
            SettingsURLEntry(name: "About", fullPath: "General > About", url: "settings-navigation://com.apple.Settings.General/About"),
            SettingsURLEntry(name: "iOS Version", fullPath: "General > About > iOS Version", url: "settings-navigation://com.apple.Settings.General/About/SW_VERSION_SPECIFIER"),
            SettingsURLEntry(name: "Certificate Trust Settings", fullPath: "General > About > Certificate Trust Settings", url: "settings-navigation://com.apple.Settings.General/About/CERT_TRUST_SETTINGS"),
            SettingsURLEntry(name: "Software Update", fullPath: "General > Software Update", url: "settings-navigation://com.apple.Settings.General/SOFTWARE_UPDATE_LINK"),
            SettingsURLEntry(name: "Automatic Updates", fullPath: "General > Software Update > Automatic Updates", url: "settings-navigation://com.apple.Settings.General/SOFTWARE_UPDATE_LINK/SUAutomaticUpdateButton"),
            SettingsURLEntry(name: "Beta Updates", fullPath: "General > Software Update > Beta Updates", url: "settings-navigation://com.apple.Settings.General/SOFTWARE_UPDATE_LINK/SUAutomaticUpdateButton"),
            SettingsURLEntry(name: "iPhone Storage", fullPath: "General > iPhone Storage", url: "settings-navigation://com.apple.Settings.General/STORAGE_MGMT"),
            SettingsURLEntry(name: "[bundle identifier]", fullPath: "General > iPhone Storage > [bundle identifier]", url: "settings-navigation://com.apple.Settings.General/STORAGE_MGMT/bundle_identifier"),
            SettingsURLEntry(name: "AppleCare & Warranty", fullPath: "General > AppleCare & Warranty", url: "settings-navigation://com.apple.Settings.General/COVERAGE"),
            SettingsURLEntry(name: "Health Data", fullPath: "General > Health Data", url: "settings-navigation://com.apple.Settings.Apps/com.apple.Health"),
            SettingsURLEntry(name: "Health Details", fullPath: "General > Health Data > Health Details", url: "settings-navigation://com.apple.Settings.Apps/com.apple.Health/HEALTH_DETAILS_ITEM"),
            SettingsURLEntry(name: "Medical ID", fullPath: "General > Health Data > Medical ID", url: "settings-navigation://com.apple.Settings.Apps/com.apple.Health/MEDICAL_ID_ITEM"),
            SettingsURLEntry(name: "Data Access & Devices", fullPath: "General > Health Data > Data Access & Devices", url: "settings-navigation://com.apple.Settings.Apps/com.apple.Health/SOURCES_ITEM"),
            SettingsURLEntry(name: "AirDrop", fullPath: "General > AirDrop", url: "settings-navigation://com.apple.Settings.General/AIRDROP_LINK"),
            SettingsURLEntry(name: "Start Sharing By – Bringing Devices Together (switch) almost unnoticeable highlighting", fullPath: "General > AirDrop > Start Sharing By – Bringing Devices Together (switch) almost unnoticeable highlighting", url: "settings-navigation://com.apple.Settings.General/AIRDROP_LINK#AIRDROP_NFC_ID"),
            SettingsURLEntry(name: "Out of Range – Use Cellular Data (switch) almost unnoticeable highlighting", fullPath: "General > AirDrop > Out of Range – Use Cellular Data (switch) almost unnoticeable highlighting", url: "settings-navigation://com.apple.Settings.General/AIRDROP_LINK#AIRDROP_CELLULAR_USAGE_ID"),
            SettingsURLEntry(name: "AirPlay & Continuity", fullPath: "General > AirPlay & Continuity", url: "settings-navigation://com.apple.Settings.General/CONTINUITY_SPEC"),
            SettingsURLEntry(name: "Picture in Picture", fullPath: "General > Picture in Picture", url: "settings-navigation://com.apple.Settings.General/PiP_SPEC"),
            SettingsURLEntry(name: "Screen Capture", fullPath: "General > Screen Capture", url: "settings-navigation://com.apple.Settings.General/SCREEN_CAPTURE"),
            SettingsURLEntry(name: "Local Capture", fullPath: "General > Local Capture", url: "settings-navigation://com.apple.Settings.General/LOCAL_CAPTURE"),
            SettingsURLEntry(name: "Matter Accessories", fullPath: "General > Matter Accessories", url: "settings-navigation://com.apple.Settings.General/MATTER_ACCESSORIES"),
            SettingsURLEntry(name: "Home Button (button) device specific", fullPath: "General > Home Button (button) device specific", url: "settings-navigation://com.apple.Settings.General#HOME_BUTTON"),
            SettingsURLEntry(name: "AutoFill & Passwords", fullPath: "General > AutoFill & Passwords", url: "settings-navigation://com.apple.Settings.General/AUTOFILL"),
            SettingsURLEntry(name: "Background App Refresh", fullPath: "General > Background App Refresh", url: "settings-navigation://com.apple.Settings.General/AUTO_CONTENT_DOWNLOAD"),
            SettingsURLEntry(name: "Date & Time", fullPath: "General > Date & Time", url: "settings-navigation://com.apple.Settings.General/DATE_AND_TIME"),
            SettingsURLEntry(name: "24-Hour Time", fullPath: "General > Date & Time > 24-Hour Time (switch)", url: "settings-navigation://com.apple.Settings.General/DATE_AND_TIME#24_HOUR_TIME"),
            SettingsURLEntry(name: "Set Automatically", fullPath: "General > Date & Time > Set Automatically (switch)", url: "settings-navigation://com.apple.Settings.General/DATE_AND_TIME#SET_AUTOMATICALLY"),
            SettingsURLEntry(name: "Time Zone", fullPath: "General > Date & Time > Time Zone (button)", url: "settings-navigation://com.apple.Settings.General/DATE_AND_TIME#TIME_ZONE"),
            SettingsURLEntry(name: "Dictionary", fullPath: "General > Dictionary", url: "settings-navigation://com.apple.Settings.General/DICTIONARY"),
            SettingsURLEntry(name: "Fonts", fullPath: "General > Fonts", url: "settings-navigation://com.apple.Settings.General/FONT_SETTING"),
            SettingsURLEntry(name: "System Fonts", fullPath: "General > Fonts > System Fonts", url: "settings-navigation://com.apple.Settings.General/FONT_SETTING/SYSTEM_FONTS"),
            SettingsURLEntry(name: "My Fonts", fullPath: "General > Fonts > My Fonts", url: "settings-navigation://com.apple.Settings.General/FONT_SETTING/USER_FONTS"),
            SettingsURLEntry(name: "More Fonts", fullPath: "General > Fonts > More Fonts", url: "settings-navigation://com.apple.Settings.General/FONT_SETTING/MORE_FONTS"),
            SettingsURLEntry(name: "Keyboard", fullPath: "General > Keyboard", url: "settings-navigation://com.apple.Settings.General/Keyboard"),
            SettingsURLEntry(name: "Keyboards", fullPath: "General > Keyboard > Keyboards", url: "settings-navigation://com.apple.Settings.General/Keyboard/KEYBOARDS"),
            SettingsURLEntry(name: "Text Replacement", fullPath: "General > Keyboard > Text Replacement", url: "settings-navigation://com.apple.Settings.General/Keyboard/USER_DICTIONARY"),
            SettingsURLEntry(name: "One-Handed Keyboard", fullPath: "General > Keyboard > One-Handed Keyboard", url: "settings-navigation://com.apple.Settings.General/Keyboard/ReachableKeyboard"),
            SettingsURLEntry(name: "Character Preview", fullPath: "General > Keyboard > Character Preview (switch)", url: "settings-navigation://com.apple.Settings.General/Keyboard#KeyboardAllowPaddle"),
            SettingsURLEntry(name: "Haptic Feedback", fullPath: "General > Keyboard > Haptic Feedback (switch)", url: "settings-navigation://com.apple.Settings.General/Keyboard#KeyboardVisceral"),
            SettingsURLEntry(name: "Sound", fullPath: "General > Keyboard > Sound (switch)", url: "settings-navigation://com.apple.Settings.General/Keyboard#keyboard-audio"),
            SettingsURLEntry(name: "Hardware Keyboard", fullPath: "General > Keyboard > Hardware Keyboard", url: "settings-navigation://com.apple.Settings.General/Keyboard/HardwareKeyboard"),
            SettingsURLEntry(name: "Auto-Capitalization", fullPath: "General > Keyboard > Auto-Capitalization (switch)", url: "settings-navigation://com.apple.Settings.General/Keyboard#KeyboardAutocapitalization"),
            SettingsURLEntry(name: "Auto-Correction", fullPath: "General > Keyboard > Auto-Correction (switch)", url: "settings-navigation://com.apple.Settings.General/Keyboard#KeyboardAutocorrection"),
            SettingsURLEntry(name: "Predictive Text", fullPath: "General > Keyboard > Predictive Text (switch)", url: "settings-navigation://com.apple.Settings.General/Keyboard#KeyboardPrediction"),
            SettingsURLEntry(name: "Show Math Results", fullPath: "General > Keyboard > Show Math Results (switch)", url: "settings-navigation://com.apple.Settings.General/Keyboard#KeyboardMathExpressionCompletion"),
            SettingsURLEntry(name: "Check Spelling", fullPath: "General > Keyboard > Check Spelling (switch)", url: "settings-navigation://com.apple.Settings.General/Keyboard#KeyboardCheckSpelling"),
            SettingsURLEntry(name: "Enable Caps Lock", fullPath: "General > Keyboard > Enable Caps Lock (switch)", url: "settings-navigation://com.apple.Settings.General/Keyboard#KeyboardCapsLock"),
            SettingsURLEntry(name: "Slide to Type", fullPath: "General > Keyboard > Slide to Type (switch)", url: "settings-navigation://com.apple.Settings.General/Keyboard#KeyboardContinuousPathEnabled"),
            SettingsURLEntry(name: "Delete Slide-to-Type by Word", fullPath: "General > Keyboard > Delete Slide-to-Type by Word (switch)", url: "settings-navigation://com.apple.Settings.General/Keyboard#KeyboardContinuousPathDeleteWholeWord"),
            SettingsURLEntry(name: "“.” Shortcut", fullPath: "General > Keyboard > “.” Shortcut (switch)", url: "settings-navigation://com.apple.Settings.General/Keyboard#KeyboardPeriodShortcut"),
            SettingsURLEntry(name: "Enable Dictation", fullPath: "General > Keyboard > Enable Dictation (switch)", url: "settings-navigation://com.apple.Settings.General/Keyboard#Dictation"),
            SettingsURLEntry(name: "Dictation – Auto-Punctuation", fullPath: "General > Keyboard > Dictation – Auto-Punctuation (switch)", url: "settings-navigation://com.apple.Settings.General/Keyboard#AutoPunctuationSetting"),
            SettingsURLEntry(name: "Dictation Languages", fullPath: "General > Keyboard > Dictation Languages", url: "settings-navigation://com.apple.Settings.General/Keyboard/DictationSettings"),
            SettingsURLEntry(name: "Dictation Shortcut", fullPath: "General > Keyboard > Dictation Shortcut", url: "settings-navigation://com.apple.Settings.General/Keyboard/DictationHWShortcut"),
            SettingsURLEntry(name: "English – Show Predictions In-Line", fullPath: "General > Keyboard > English – Show Predictions In-Line", url: "settings-navigation://com.apple.Settings.General/Keyboard#KeyboardInlineCompletion"),
            SettingsURLEntry(name: "Emoji – Stickers", fullPath: "General > Keyboard > Emoji – Stickers", url: "settings-navigation://com.apple.Settings.General/Keyboard#ShowStickers"),
            SettingsURLEntry(name: "Language & Region", fullPath: "General > Language & Region", url: "settings-navigation://com.apple.Settings.General/INTERNATIONAL"),
            SettingsURLEntry(name: "Add Language", fullPath: "General > Language & Region > Add Language", url: "settings-navigation://com.apple.Settings.General/INTERNATIONAL/ADD_PREFERRED_LANGUAGE"),
            SettingsURLEntry(name: "Region", fullPath: "General > Language & Region > Region", url: "settings-navigation://com.apple.Settings.General/INTERNATIONAL/LOCALE"),
            SettingsURLEntry(name: "Calendar", fullPath: "General > Language & Region > Calendar", url: "settings-navigation://com.apple.Settings.General/INTERNATIONAL/CALENDAR"),
            SettingsURLEntry(name: "Temperature", fullPath: "General > Language & Region > Temperature", url: "settings-navigation://com.apple.Settings.General/INTERNATIONAL/TEMPERATURE_UNIT"),
            SettingsURLEntry(name: "Measurement System", fullPath: "General > Language & Region > Measurement System", url: "settings-navigation://com.apple.Settings.General/INTERNATIONAL/MEASUREMENT_SYSTEM"),
            SettingsURLEntry(name: "First Day of Week", fullPath: "General > Language & Region > First Day of Week", url: "settings-navigation://com.apple.Settings.General/INTERNATIONAL/FIRST_WEEKDAY"),
            SettingsURLEntry(name: "Date Format", fullPath: "General > Language & Region > Date Format", url: "settings-navigation://com.apple.Settings.General/INTERNATIONAL/DATE_FORMAT"),
            SettingsURLEntry(name: "Number Format", fullPath: "General > Language & Region > Number Format", url: "settings-navigation://com.apple.Settings.General/INTERNATIONAL/NUMBER_FORMAT"),
            SettingsURLEntry(name: "Live Text", fullPath: "General > Language & Region > Live Text (switch)", url: "settings-navigation://com.apple.Settings.General/INTERNATIONAL#LIVE_TEXT_CELL"),
            SettingsURLEntry(name: "Trackpad & Mouse", fullPath: "General > Trackpad & Mouse", url: "settings-navigation://com.apple.Settings.General/POINTERS"),
            SettingsURLEntry(name: "VPN & Device Management", fullPath: "General > VPN & Device Management", url: "settings-navigation://com.apple.Settings.General/ManagedConfigurationList"),
            SettingsURLEntry(name: "VPN", fullPath: "General > VPN & Device Management > VPN", url: "settings-navigation://com.apple.Settings.General/ManagedConfigurationList/VPN"),
            SettingsURLEntry(name: "Legal & Regulatory", fullPath: "General > Legal & Regulatory", url: "settings-navigation://com.apple.Settings.General/LEGAL_AND_REGULATORY"),
            SettingsURLEntry(name: "Transfer or Reset iPhone", fullPath: "General > Transfer or Reset iPhone", url: "settings-navigation://com.apple.Settings.General/Reset"),
            SettingsURLEntry(name: "Shut Down", fullPath: "General > Shut Down (button)", url: "settings-navigation://com.apple.Settings.General#SHUTDOWN_LABEL"),
        ]),
        SettingsURLCategory(name: "Accessibility", icon: "accessibility", entries: [
            SettingsURLEntry(name: "Accessibility", fullPath: "Accessibility", url: "settings-navigation://com.apple.Settings.Accessibility"),
            SettingsURLEntry(name: "VoiceOver", fullPath: "Accessibility > VoiceOver", url: "settings-navigation://com.apple.Settings.Accessibility/VOICEOVER_TITLE"),
            SettingsURLEntry(name: "Zoom", fullPath: "Accessibility > Zoom", url: "settings-navigation://com.apple.Settings.Accessibility/ZOOM_TITLE"),
            SettingsURLEntry(name: "Hover Text", fullPath: "Accessibility > Hover Text", url: "settings-navigation://com.apple.Settings.Accessibility/HOVERTEXT_TITLE"),
            SettingsURLEntry(name: "Display & Text Size", fullPath: "Accessibility > Display & Text Size", url: "settings-navigation://com.apple.Settings.Accessibility/DISPLAY_AND_TEXT"),
            SettingsURLEntry(name: "Bold Text", fullPath: "Accessibility > Display & Text Size > Bold Text (switch)", url: "settings-navigation://com.apple.Settings.Accessibility/DISPLAY_AND_TEXT/ENHANCE_TEXT_LEGIBILITY"),
            SettingsURLEntry(name: "Larger Text", fullPath: "Accessibility > Display & Text Size > Larger Text", url: "settings-navigation://com.apple.Settings.Accessibility/DISPLAY_AND_TEXT/LARGER_TEXT"),
            SettingsURLEntry(name: "Show Borders", fullPath: "Accessibility > Display & Text Size > Show Borders (switch)", url: "settings-navigation://com.apple.Settings.Accessibility/DISPLAY_AND_TEXT/BUTTON_SHAPES"),
            SettingsURLEntry(name: "On/Off Labels", fullPath: "Accessibility > Display & Text Size > On/Off Labels (switch)", url: "settings-navigation://com.apple.Settings.Accessibility/DISPLAY_AND_TEXT/ON_OFF_LABELS"),
            SettingsURLEntry(name: "Reduce Transparency", fullPath: "Accessibility > Display & Text Size > Reduce Transparency (switch)", url: "settings-navigation://com.apple.Settings.Accessibility/DISPLAY_AND_TEXT/REDUCE_TRANSPARENCY"),
            SettingsURLEntry(name: "Increase Contrast", fullPath: "Accessibility > Display & Text Size > Increase Contrast (switch)", url: "settings-navigation://com.apple.Settings.Accessibility/DISPLAY_AND_TEXT/TEXT_COLORS_DARKEN"),
            SettingsURLEntry(name: "Differentiate Without Color", fullPath: "Accessibility > Display & Text Size > Differentiate Without Color (switch)", url: "settings-navigation://com.apple.Settings.Accessibility/DISPLAY_AND_TEXT/DIFFERENTIATE_WITHOUT_COLOR"),
            SettingsURLEntry(name: "Prefer Horizontal Text", fullPath: "Accessibility > Display & Text Size > Prefer Horizontal Text (switch)", url: "settings-navigation://com.apple.Settings.Accessibility/DISPLAY_AND_TEXT/PREFER_HORIZONTAL_TEXT"),
            SettingsURLEntry(name: "Smart Invert", fullPath: "Accessibility > Display & Text Size > Smart Invert (switch)", url: "settings-navigation://com.apple.Settings.Accessibility/DISPLAY_AND_TEXT/SMART_INVERT"),
            SettingsURLEntry(name: "Classic Invert", fullPath: "Accessibility > Display & Text Size > Classic Invert (switch)", url: "settings-navigation://com.apple.Settings.Accessibility/DISPLAY_AND_TEXT/CLASSIC_INVERT"),
            SettingsURLEntry(name: "Color Filters", fullPath: "Accessibility > Display & Text Size > Color Filters", url: "settings-navigation://com.apple.Settings.Accessibility/DISPLAY_AND_TEXT/DISPLAY_FILTER_COLOR"),
            SettingsURLEntry(name: "Reduce White Point", fullPath: "Accessibility > Display & Text Size > Reduce White Point (switch/slider)", url: "settings-navigation://com.apple.Settings.Accessibility/DISPLAY_AND_TEXT/WHITE_POINT"),
            SettingsURLEntry(name: "Auto-Brightness", fullPath: "Accessibility > Display & Text Size > Auto-Brightness (switch)", url: "settings-navigation://com.apple.Settings.Accessibility/DISPLAY_AND_TEXT/AUTO_BRIGHTNESS"),
            SettingsURLEntry(name: "Motion", fullPath: "Accessibility > Motion", url: "settings-navigation://com.apple.Settings.Accessibility/MOTION_TITLE"),
            SettingsURLEntry(name: "Reduce Motion", fullPath: "Accessibility > Motion > Reduce Motion (switch)", url: "settings-navigation://com.apple.Settings.Accessibility/MOTION_TITLE#REDUCE_MOTION"),
            SettingsURLEntry(name: "Prefer Cross-Fade Transitions (switch) If Reduce Motion is enabled", fullPath: "Accessibility > Motion > Prefer Cross-Fade Transitions (switch) If Reduce Motion is enabled", url: "settings-navigation://com.apple.Settings.Accessibility/MOTION_TITLE/REDUCE_MOTION_REDUCE_SLIDE_ANIMATIONS"),
            SettingsURLEntry(name: "Vehicle Motion Clues", fullPath: "Accessibility > Motion > Vehicle Motion Clues", url: "settings-navigation://com.apple.Settings.Accessibility/MOTION_TITLE/MotionCues"),
            SettingsURLEntry(name: "Dim Flashing Lights", fullPath: "Accessibility > Motion > Dim Flashing Lights (switch)", url: "settings-navigation://com.apple.Settings.Accessibility/MOTION_TITLE/PHOTOSENSITIVE_MITIGATION"),
            SettingsURLEntry(name: "Auto-Play Animated Images", fullPath: "Accessibility > Motion > Auto-Play Animated Images (switch)", url: "settings-navigation://com.apple.Settings.Accessibility/MOTION_TITLE/REDUCE_MOTION_AUTOPLAY_ANIMATED_IMAGES"),
            SettingsURLEntry(name: "Auto-Play Video Previews", fullPath: "Accessibility > Motion > Auto-Play Video Previews (switch)", url: "settings-navigation://com.apple.Settings.Accessibility/MOTION_TITLE/REDUCE_MOTION_AUTOPLAY_VIDEO_PREVIEWS"),
            SettingsURLEntry(name: "Auto-Play Message Effects", fullPath: "Accessibility > Motion > Auto-Play Message Effects (switch)", url: "settings-navigation://com.apple.Settings.Accessibility/MOTION_TITLE/ReduceMotionAutoplayMessagesEffects"),
            SettingsURLEntry(name: "Prefer Non-Blinking Cursor", fullPath: "Accessibility > Motion > Prefer Non-Blinking Cursor (switch)", url: "settings-navigation://com.apple.Settings.Accessibility/MOTION_TITLE/PREFER_NONBLINKING_CURSOR"),
            SettingsURLEntry(name: "Read & Speak", fullPath: "Accessibility > Read & Speak", url: "settings-navigation://com.apple.Settings.Accessibility/SPEECH_TITLE"),
            SettingsURLEntry(name: "Accessibility Reader", fullPath: "Accessibility > Read & Speak > Accessibility Reader", url: "settings-navigation://com.apple.Settings.Accessibility/SPEECH_TITLE/AccessibilityReader"),
            SettingsURLEntry(name: "Speak Screen", fullPath: "Accessibility > Read & Speak > Speak Screen", url: "settings-navigation://com.apple.Settings.Accessibility/SPEECH_TITLE/SpeakScreen"),
            SettingsURLEntry(name: "Speak Selection", fullPath: "Accessibility > Read & Speak > Speak Selection", url: "settings-navigation://com.apple.Settings.Accessibility/SPEECH_TITLE/SpeakSelection"),
            SettingsURLEntry(name: "Audio Descriptions", fullPath: "Accessibility > Audio Descriptions", url: "settings-navigation://com.apple.Settings.Accessibility/DESCRIPTIVE_VIDEO"),
            SettingsURLEntry(name: "Touch", fullPath: "Accessibility > Touch", url: "settings-navigation://com.apple.Settings.Accessibility/TOUCH_REACHABILITY_TITLE"),
            SettingsURLEntry(name: "AssistiveTouch", fullPath: "Accessibility > Touch > AssistiveTouch", url: "settings-navigation://com.apple.Settings.Accessibility/TOUCH_REACHABILITY_TITLE/AIR_TOUCH_TITLE"),
            SettingsURLEntry(name: "Reachability", fullPath: "Accessibility > Touch > Reachability (switch)", url: "settings-navigation://com.apple.Settings.Accessibility/TOUCH_REACHABILITY_TITLE/REACHABILITY"),
            SettingsURLEntry(name: "Haptic Touch", fullPath: "Accessibility > Touch > Haptic Touch", url: "settings-navigation://com.apple.Settings.Accessibility/TOUCH_REACHABILITY_TITLE/ForceTouch"),
            SettingsURLEntry(name: "Touch Accomodations", fullPath: "Accessibility > Touch > Touch Accomodations", url: "settings-navigation://com.apple.Settings.Accessibility/TOUCH_REACHABILITY_TITLE/TOUCH_ACCOMMODATIONS"),
            SettingsURLEntry(name: "Shake to Undo", fullPath: "Accessibility > Touch > Shake to Undo (switch)", url: "settings-navigation://com.apple.Settings.Accessibility/TOUCH_REACHABILITY_TITLE/SHAKE_TO_UNDO"),
            SettingsURLEntry(name: "Vibration", fullPath: "Accessibility > Touch > Vibration (switch)", url: "settings-navigation://com.apple.Settings.Accessibility/TOUCH_REACHABILITY_TITLE/VIBRATION"),
            SettingsURLEntry(name: "Prevent Lock to End Call", fullPath: "Accessibility > Touch > Prevent Lock to End Call (switch)", url: "settings-navigation://com.apple.Settings.Accessibility/TOUCH_REACHABILITY_TITLE/LockButtonIgnore"),
            SettingsURLEntry(name: "Call Audio Routing", fullPath: "Accessibility > Touch > Call Audio Routing", url: "settings-navigation://com.apple.Settings.Accessibility/TOUCH_REACHABILITY_TITLE/CALL_AUDIO_ROUTING"),
            SettingsURLEntry(name: "Back Tap", fullPath: "Accessibility > Touch > Back Tap", url: "settings-navigation://com.apple.Settings.Accessibility/TOUCH_REACHABILITY_TITLE/BackTap"),
            SettingsURLEntry(name: "Prefer Single-Touch Actions", fullPath: "Accessibility > Touch  > Prefer Single-Touch Actions (switch)", url: "settings-navigation://com.apple.Settings.Accessibility/TOUCH_REACHABILITY_TITLE#Prefer%20Single-Touch%20Actions"),
            SettingsURLEntry(name: "Switch Control", fullPath: "Accessibility > Switch Control", url: "settings-navigation://com.apple.Settings.Accessibility/ScannerSwitchTitle"),
            SettingsURLEntry(name: "Voice Control", fullPath: "Accessibility > Voice Control", url: "settings-navigation://com.apple.Settings.Accessibility/CommandAndControlTitle"),
            SettingsURLEntry(name: "Eye Tracking", fullPath: "Accessibility > Eye Tracking", url: "settings-navigation://com.apple.Settings.Accessibility/OnDeviceEyeTracking"),
            SettingsURLEntry(name: "Head Tracking", fullPath: "Accessibility > Head Tracking", url: "settings-navigation://com.apple.Settings.Accessibility/AST_HEAD_TRACKING"),
            SettingsURLEntry(name: "Home Button device specific", fullPath: "Accessibility > Home Button device specific", url: "settings-navigation://com.apple.Settings.Accessibility/HOME_CLICK_TITLE"),
            SettingsURLEntry(name: "Face ID & Attention", fullPath: "Accessibility > Face ID & Attention", url: "settings-navigation://com.apple.Settings.Accessibility/FACE_ID"),
            SettingsURLEntry(name: "Attention Aware Features", fullPath: "Accessibility > Face ID & Attention > Attention Aware Features (switch)", url: "settings-navigation://com.apple.Settings.Accessibility/FACE_ID/AttentionAware"),
            SettingsURLEntry(name: "Control Nearby Devices", fullPath: "Accessibility > Control Nearby Devices", url: "settings-navigation://com.apple.Settings.Accessibility/CONTROL_NEARBY_DEVICES"),
            SettingsURLEntry(name: "Control Nearby Devices", fullPath: "Accessibility > Control Nearby Devices > Control Nearby Devices (button)", url: "settings-navigation://com.apple.Settings.Accessibility/CONTROL_NEARBY_DEVICES/CONTROL_NEARBY_DEVICES"),
            SettingsURLEntry(name: "Hearing Devices", fullPath: "Accessibility > Hearing Devices", url: "settings-navigation://com.apple.Settings.Accessibility/HEARING_AID_TITLE"),
            SettingsURLEntry(name: "Hearing Control Center", fullPath: "Accessibility > Hearing Control Center", url: "settings-navigation://com.apple.Settings.Accessibility/HEARING_CONTROL_CENTER"),
            SettingsURLEntry(name: "Sound & Name Recognition", fullPath: "Accessibility > Sound & Name Recognition", url: "settings-navigation://com.apple.Settings.Accessibility/SOUND_AND_NAME_RECOGNITION_TITLE"),
            SettingsURLEntry(name: "RTT/TTY", fullPath: "Accessibility > RTT/TTY", url: "settings-navigation://com.apple.Settings.Accessibility/RTT"),
            SettingsURLEntry(name: "Audio & Visual", fullPath: "Accessibility > Audio & Visual", url: "settings-navigation://com.apple.Settings.Accessibility/AUDIO_VISUAL_TITLE"),
            SettingsURLEntry(name: "Headphone Accommodations", fullPath: "Accessibility > Audio & Visual > Headphone Accommodations", url: "settings-navigation://com.apple.Settings.Accessibility/AUDIO_VISUAL_TITLE/AXPAEnableSpecID"),
            SettingsURLEntry(name: "Background Sounds", fullPath: "Accessibility > Audio & Visual > Background Sounds", url: "settings-navigation://com.apple.Settings.Accessibility/AUDIO_VISUAL_TITLE/AXCSEnableSpecID"),
            SettingsURLEntry(name: "Live Listen", fullPath: "Accessibility > Audio & Visual > Live Listen", url: "settings-navigation://com.apple.Settings.Accessibility/AUDIO_VISUAL_TITLE/AXLLEnableSpecID"),
            SettingsURLEntry(name: "Mono Audio", fullPath: "Accessibility > Audio & Visual > Mono Audio (switch)", url: "settings-navigation://com.apple.Settings.Accessibility/AUDIO_VISUAL_TITLE/AXPAMonoSpecID"),
            SettingsURLEntry(name: "Always Show Volume Controls", fullPath: "Accessibility > Audio & Visual > Always Show Volume Controls (switch)", url: "settings-navigation://com.apple.Settings.Accessibility/AUDIO_VISUAL_TITLE/AXPAAlwaysShowVolumeControlSpecID"),
            SettingsURLEntry(name: "Add Voice Isolation", fullPath: "Accessibility > Audio & Visual > Add Voice Isolation (switch)", url: "settings-navigation://com.apple.Settings.Accessibility/AUDIO_VISUAL_TITLE#ExtendedVoiceIsolationSpecID"),
            SettingsURLEntry(name: "Headphone Notifications", fullPath: "Accessibility > Audio & Visual > Headphone Notifications (switch)", url: "settings-navigation://com.apple.Settings.Accessibility/AUDIO_VISUAL_TITLE/AXHeadphoneNotificationsSpecID"),
            SettingsURLEntry(name: "Balance", fullPath: "Accessibility > Audio & Visual > Balance (slider)", url: "settings-navigation://com.apple.Settings.Accessibility/AUDIO_VISUAL_TITLE/LeftRightBalance"),
            SettingsURLEntry(name: "Add Audio in Calls", fullPath: "Accessibility > Audio & Visual > Add Audio in Calls", url: "settings-navigation://com.apple.Settings.Accessibility/AUDIO_VISUAL_TITLE/MIX_TO_UPLINK"),
            SettingsURLEntry(name: "Call Audio Routing", fullPath: "Accessibility > Audio & Visual > Call Audio Routing", url: "settings-navigation://com.apple.Settings.Accessibility/AUDIO_VISUAL_TITLE/CALL_AUDIO_ROUTING"),
            SettingsURLEntry(name: "LED Flash for Alerts", fullPath: "Accessibility > Audio & Visual > LED Flash for Alerts", url: "settings-navigation://com.apple.Settings.Accessibility/AUDIO_VISUAL_TITLE/LED_FLASH"),
            SettingsURLEntry(name: "Subtitles & Captioning", fullPath: "Accessibility > Subtitles & Captioning", url: "settings-navigation://com.apple.Settings.Accessibility/SUBTITLES_CAPTIONING"),
            SettingsURLEntry(name: "Closed Captions + SDH", fullPath: "Accessibility > Subtitles & Captioning > Closed Captions + SDH (switch)", url: "settings-navigation://com.apple.Settings.Accessibility/SUBTITLES_CAPTIONING#PREFER_SDH"),
            SettingsURLEntry(name: "Style", fullPath: "Accessibility > Subtitles & Captioning > Style", url: "settings-navigation://com.apple.Settings.Accessibility/SUBTITLES_CAPTIONING/currentTheme"),
            SettingsURLEntry(name: "Show Audio Transcriptions", fullPath: "Accessibility > Subtitles & Captioning > Show Audio Transcriptions (switch)", url: "settings-navigation://com.apple.Settings.Accessibility/SUBTITLES_CAPTIONING/SHOW_AUDIO_TRANSCRIPTIONS"),
            SettingsURLEntry(name: "Show when Muted", fullPath: "Accessibility > Subtitles & Captioning > Show when Muted (switch)", url: "settings-navigation://com.apple.Settings.Accessibility/SUBTITLES_CAPTIONING/SHOW_WHEN_MUTED"),
            SettingsURLEntry(name: "Show on Skip Back", fullPath: "Accessibility > Subtitles & Captioning > Show on Skip Back (switch)", url: "settings-navigation://com.apple.Settings.Accessibility/SUBTITLES_CAPTIONING/SHOW_ON_SKIP_BACK"),
            SettingsURLEntry(name: "Live Captions", fullPath: "Accessibility > Live Captions", url: "settings-navigation://com.apple.Settings.Accessibility/LIVE_TRANSCRIPTION"),
            SettingsURLEntry(name: "Live Speech", fullPath: "Accessibility > Live Speech", url: "settings-navigation://com.apple.Settings.Accessibility/LIVE_SPEECH_TITLE"),
            SettingsURLEntry(name: "Phrases", fullPath: "Accessibility > Live Speech > Phrases", url: "settings-navigation://com.apple.Settings.Accessibility/LIVE_SPEECH_TITLE/PHRASES"),
            SettingsURLEntry(name: "Personal Voice", fullPath: "Accessibility > Personal Voice", url: "settings-navigation://com.apple.Settings.Accessibility/PERSONAL_VOICE_TITLE"),
            SettingsURLEntry(name: "Vocal Shortcuts", fullPath: "Accessibility > Vocal Shortcuts", url: "settings-navigation://com.apple.Settings.Accessibility/ADAPTIVE_VOICE_SHORTCUTS_TITLE"),
            SettingsURLEntry(name: "Keyboards & Typing", fullPath: "Accessibility > Keyboards & Typing", url: "settings-navigation://com.apple.Settings.Accessibility/KEYBOARDS"),
            SettingsURLEntry(name: "AirPods", fullPath: "Accessibility > AirPods", url: "settings-navigation://com.apple.Settings.Accessibility/AIRPODS"),
            SettingsURLEntry(name: "Spatial Audio Head Tracking – Follow iPhone", fullPath: "Accessibility > AirPods > Spatial Audio Head Tracking – Follow iPhone (switch)", url: "settings-navigation://com.apple.Settings.Accessibility/AIRPODS#SPATIAL_AUDIO_SWITCH"),
            SettingsURLEntry(name: "Guided Access", fullPath: "Accessibility > Guided Access", url: "settings-navigation://com.apple.Settings.Accessibility/GUIDED_ACCESS_TITLE"),
            SettingsURLEntry(name: "Passcode Settings", fullPath: "Accessibility > Guided Access > Passcode Settings", url: "settings-navigation://com.apple.Settings.Accessibility/GUIDED_ACCESS_TITLE/GuidedAccessSecurityLinkList"),
            SettingsURLEntry(name: "Time Limits", fullPath: "Accessibility > Guided Access > Time Limits", url: "settings-navigation://com.apple.Settings.Accessibility/GUIDED_ACCESS_TITLE/GuidedAccessTimeRestrictionsLinkList"),
            SettingsURLEntry(name: "Accessibility Shortcut", fullPath: "Accessibility > Guided Access > Accessibility Shortcut (switch)", url: "settings-navigation://com.apple.Settings.Accessibility/GUIDED_ACCESS_TITLE#GuidedAccessEnableAXFeatures"),
            SettingsURLEntry(name: "Display Auto-Lock", fullPath: "Accessibility > Guided Access > Display Auto-Lock", url: "settings-navigation://com.apple.Settings.Accessibility/GUIDED_ACCESS_TITLE/GuidedAccessAutoLockTime#GuidedAccessAutoLockTime"),
            SettingsURLEntry(name: "Assistive Access", fullPath: "Accessibility > Assistive Access", url: "settings-navigation://com.apple.Settings.Accessibility/CLARITY_UI_TITLE"),
            SettingsURLEntry(name: "Accessibility Shortcut", fullPath: "Accessibility > Accessibility Shortcut", url: "settings-navigation://com.apple.Settings.Accessibility/TRIPLE_CLICK_TITLE"),
            SettingsURLEntry(name: "Per-App Settings", fullPath: "Accessibility > Per-App Settings", url: "settings-navigation://com.apple.Settings.Accessibility/APP_AX_SETTINGS_TITLE"),
            SettingsURLEntry(name: "Show Hidden Apps", fullPath: "Accessibility > Per-App Settings > Show Hidden Apps", url: "settings-navigation://com.apple.Settings.Accessibility/APP_AX_SETTINGS_TITLE/PROTECTED_APPS_SHOW_HIDDEN_TITLE"),
            SettingsURLEntry(name: "Add App", fullPath: "Accessibility > Per-App Settings > Add App (dialog)", url: "settings-navigation://com.apple.Settings.Accessibility/APP_AX_SETTINGS_TITLE/AX_ADD_BUTTON_IDENTIFIER"),
            SettingsURLEntry(name: "[bundle identifier] as long as you have added the app there, otherwise goes to the parent page", fullPath: "Accessibility > Per-App Settings > [bundle identifier] as long as you have added the app there, otherwise goes to the parent page", url: "settings-navigation://com.apple.Settings.Accessibility/APP_AX_SETTINGS_TITLE/bundle_identifier"),
        ]),
        SettingsURLCategory(name: "Action Button device specific", icon: "button.programmable", entries: [
            SettingsURLEntry(name: "Action Button device specific", fullPath: "Action Button device specific", url: "settings-navigation://com.apple.Settings.ActionButton"),
        ]),
        SettingsURLCategory(name: "Camera", icon: "camera", entries: [
            SettingsURLEntry(name: "Camera", fullPath: "Camera", url: "settings-navigation://com.apple.Settings.Camera"),
            SettingsURLEntry(name: "Record Video", fullPath: "Camera > Record Video", url: "settings-navigation://com.apple.Settings.Camera/CameraVideoSettingsList"),
            SettingsURLEntry(name: "Record Slo-mo", fullPath: "Camera > Record Slo-mo", url: "settings-navigation://com.apple.Settings.Camera/CameraSlomoSettingsList"),
            SettingsURLEntry(name: "Formats", fullPath: "Camera > Formats", url: "settings-navigation://com.apple.Settings.Camera/CameraFormatsSettingsList"),
            SettingsURLEntry(name: "Preserve Settings", fullPath: "Camera > Preserve Settings", url: "settings-navigation://com.apple.Settings.Camera/CameraPreserveSettingsSwitch"),
            SettingsURLEntry(name: "Use Volume Up for Burst", fullPath: "Camera > Use Volume Up for Burst (switch)", url: "settings-navigation://com.apple.Settings.Camera#VOLUME_UP_BURST"),
            SettingsURLEntry(name: "Scan QR Codes", fullPath: "Camera > Scan QR Codes (switch)", url: "settings-navigation://com.apple.Settings.Camera#CameraQRBannerSwitch"),
            SettingsURLEntry(name: "Show Detected Text", fullPath: "Camera > Show Detected Text (swtich)", url: "settings-navigation://com.apple.Settings.Camera#TEXT_ANALYSIS"),
            SettingsURLEntry(name: "Composition – Grid", fullPath: "Camera > Composition – Grid (switch)", url: "settings-navigation://com.apple.Settings.Camera#CameraGridSwitch"),
            SettingsURLEntry(name: "Composition – Level", fullPath: "Camera > Composition – Level (switch)", url: "settings-navigation://com.apple.Settings.Camera#CameraGridSwitch"),
            SettingsURLEntry(name: "Mirror Front Camera", fullPath: "Camera > Mirror Front Camera (switch)", url: "settings-navigation://com.apple.Settings.Camera#MIRROR"),
            SettingsURLEntry(name: "Indicators", fullPath: "Camera > Indicators", url: "settings-navigation://com.apple.Settings.Camera/CameraIndicatorsSettingsList"),
            SettingsURLEntry(name: "Photographic Styles", fullPath: "Camera > Photographic Styles (button)", url: "settings-navigation://com.apple.Settings.Camera#PHOTOGRAPHIC_STYLES"),
            SettingsURLEntry(name: "Prioritize Faster Shooting", fullPath: "Camera > Prioritize Faster Shooting (switch)", url: "settings-navigation://com.apple.Settings.Camera#CAM_CAPTURE_DYNAMIC_SHUTTER_SWITCH"),
            SettingsURLEntry(name: "Lock Screen Swipe to Open Camera", fullPath: "Camera > Lock Screen Swipe to Open Camera (switch)", url: "settings-navigation://com.apple.Settings.Camera#LOCK_SCREEN_SWIPE_SWITCH"),
            SettingsURLEntry(name: "Messages – Save Captures to Photo Library", fullPath: "Camera > Messages – Save Captures to Photo Library (switch)", url: "settings-navigation://com.apple.Settings.Camera#CAM_SAVE_MESSAGES_ASSETS_PHOTO_LIBRARY_SWITCH"),
        ]),
        SettingsURLCategory(name: "Control Center", icon: "switch.2", entries: [
            SettingsURLEntry(name: "Control Center", fullPath: "Control Center", url: "settings-navigation://com.apple.Settings.ControlCenter"),
            SettingsURLEntry(name: "Access Within Apps", fullPath: "Control Center > Access Within Apps (switch)", url: "settings-navigation://com.apple.Settings.ControlCenter#ACCESS_WITHIN_APP"),
            SettingsURLEntry(name: "Reset Control Center", fullPath: "Control Center > Reset Control Center", url: "settings-navigation://com.apple.Settings.ControlCenter#RESET_CONTROL_CENTER"),
        ]),
        SettingsURLCategory(name: "Display & Brightness", icon: "sun.max", entries: [
            SettingsURLEntry(name: "Display & Brightness", fullPath: "Display & Brightness", url: "settings-navigation://com.apple.Settings.Display"),
            SettingsURLEntry(name: "Appearance", fullPath: "Display & Brightness > Appearance (section)", url: "settings-navigation://com.apple.Settings.Display#DEVICE_APPEARANCE"),
            SettingsURLEntry(name: "Automatic", fullPath: "Display & Brightness > Appearance > Automatic (switch)", url: "settings-navigation://com.apple.Settings.Display#AUTOMATIC"),
            SettingsURLEntry(name: "Text Size", fullPath: "Display & Brightness > Text Size", url: "settings-navigation://com.apple.Settings.Display/TEXT_SIZE"),
            SettingsURLEntry(name: "Bold Text", fullPath: "Display & Brightness > Bold Text (switch)", url: "settings-navigation://com.apple.Settings.Display#BOLD_TEXT"),
            SettingsURLEntry(name: "Brightness", fullPath: "Display & Brightness > Brightness (slider)", url: "settings-navigation://com.apple.Settings.Display#BRIGHTNESS"),
            SettingsURLEntry(name: "True Tone", fullPath: "Display & Brightness > True Tone (switch)", url: "settings-navigation://com.apple.Settings.Display#WHITE_BALANCE"),
            SettingsURLEntry(name: "Night Shift", fullPath: "Display & Brightness > Night Shift", url: "settings-navigation://com.apple.Settings.Display/BLUE_LIGHT_REDUCTION"),
            SettingsURLEntry(name: "Auto-Lock", fullPath: "Display & Brightness > Auto-Lock", url: "settings-navigation://com.apple.Settings.Display/AUTOLOCK"),
            SettingsURLEntry(name: "Raise to Wake", fullPath: "Display & Brightness > Raise to Wake (switch)", url: "settings-navigation://com.apple.Settings.Display#RAISE_TO_WAKE"),
            SettingsURLEntry(name: "Display Zoom", fullPath: "Display & Brightness > Display Zoom", url: "settings-navigation://com.apple.Settings.Display/MAGNIFY"),
            SettingsURLEntry(name: "Liquid Glass", fullPath: "Dispaly & Brightness > Liquid Glass", url: "settings-navigation://com.apple.Settings.Display/LIQUID_GLASS"),
        ]),
        SettingsURLCategory(name: "Home Screen & App Library", icon: "square.grid.3x3", entries: [
            SettingsURLEntry(name: "Home Screen & App Library", fullPath: "Home Screen & App Library", url: "settings-navigation://com.apple.Settings.HomeScreenAndAppLibrary"),
            SettingsURLEntry(name: "Notifications Badges – Show in App Library (switch) almost unnoticeable highlighting", fullPath: "Home Screen & App Library > Notifications Badges – Show in App Library (switch) almost unnoticeable highlighting", url: "settings-navigation://com.apple.Settings.HomeScreenAndAppLibrary#BADGES_IN_APP_LIBRARY"),
            SettingsURLEntry(name: "Search – Show on Home Screen (switch) almost unnoticeable highlighting", fullPath: "Home Screen & App Library > Search – Show on Home Screen (switch) almost unnoticeable highlighting", url: "settings-navigation://com.apple.Settings.HomeScreenAndAppLibrary#SHOW_SEARCH_ON_HOME_SCREEN"),
        ]),
        SettingsURLCategory(name: "Search", icon: "magnifyingglass", entries: [
            SettingsURLEntry(name: "Search", fullPath: "Search", url: "settings-navigation://com.apple.Settings.Search"),
        ]),
        SettingsURLCategory(name: "Siri", icon: "mic.circle", entries: [
            SettingsURLEntry(name: "Siri", fullPath: "Siri", url: "settings-navigation://com.apple.Settings.Siri"),
        ]),
        SettingsURLCategory(name: "StandBy", icon: "clock.badge.checkmark", entries: [
            SettingsURLEntry(name: "StandBy", fullPath: "StandBy", url: "settings-navigation://com.apple.Settings.StandBy"),
            SettingsURLEntry(name: "Display device specific", fullPath: "StandBy > Display device specific", url: "settings-navigation://com.apple.Settings.StandBy/ALWAYS_ON_DISPLAY_OPTIONS"),
            SettingsURLEntry(name: "StandBy", fullPath: "StandBy > StandBy (switch)", url: "settings-navigation://com.apple.Settings.StandBy#AMBIENT_MODE_ENABLED"),
            SettingsURLEntry(name: "Night Mode", fullPath: "StandBy > Night Mode (switch)", url: "settings-navigation://com.apple.Settings.StandBy#BUMP_TO_WAKE_ENABLED"),
            SettingsURLEntry(name: "Show Notifications", fullPath: "StandBy > Show Notifications (switch)", url: "settings-navigation://com.apple.Settings.StandBy#NOTIFICATIONS_ENABLED"),
            SettingsURLEntry(name: "Show Preview on Tap Only", fullPath: "StandBy > Show Preview on Tap Only (switch)", url: "settings-navigation://com.apple.Settings.StandBy#NOTIFICATIONS_PREVIEW"),
        ]),
        SettingsURLCategory(name: "Wallpaper", icon: "photo", entries: [
            SettingsURLEntry(name: "Wallpaper", fullPath: "Wallpaper", url: "settings-navigation://com.apple.Settings.Wallpaper"),
            SettingsURLEntry(name: "Add New Wallpaper", fullPath: "Wallpaper > Add New Wallpaper", url: "settings-navigation://com.apple.Settings.Wallpaper/addNewWallpaper"),
        ]),
        SettingsURLCategory(name: "Notifications", icon: "bell", entries: [
            SettingsURLEntry(name: "Notifications", fullPath: "Notifications", url: "settings-navigation://com.apple.Settings.Notifications"),
            SettingsURLEntry(name: "Scheduled Summary", fullPath: "Notifications > Scheduled Summary", url: "settings-navigation://com.apple.Settings.Notifications/SCHEDULED_DELIVERY_ID"),
            SettingsURLEntry(name: "Show Previews", fullPath: "Notifications > Show Previews", url: "settings-navigation://com.apple.Settings.Notifications/SHOW_PREVIEW_GROUP_ID"),
            SettingsURLEntry(name: "Screen Sharing", fullPath: "Notifications > Screen Sharing", url: "settings-navigation://com.apple.Settings.Notifications/SCREENSHARING_ID"),
            SettingsURLEntry(name: "Announce Notifications", fullPath: "Notifications > Announce Notifications (button)", url: "settings-navigation://com.apple.Settings.Notifications#SPOKEN_NOTIFICATIONS_ID"),
            SettingsURLEntry(name: "Siri Suggestions", fullPath: "Notifications > Siri Suggestions", url: "settings-navigation://com.apple.Settings.Notifications/SIRI_SUGGESTIONS_ID"),
            SettingsURLEntry(name: "[bundle identifier]", fullPath: "Notifications > [bundle identifier]", url: "settings-navigation://com.apple.Settings.Notifications/bundle_identifier"),
            SettingsURLEntry(name: "Banner Style", fullPath: "Notifications > [bundle identifier] > Banner Style", url: "settings-navigation://com.apple.Settings.Notifications/bundle_identifier/BANNER_STYLE_ID"),
            SettingsURLEntry(name: "Show Previews", fullPath: "Notifications > [bundle identifier] > Show Previews", url: "settings-navigation://com.apple.Settings.Notifications/bundle_identifier/SHOW_PREVIEW_GROUP_ID"),
            SettingsURLEntry(name: "Notification Grouping", fullPath: "Notifications > [bundle identifier] > Notification Grouping", url: "settings-navigation://com.apple.Settings.Notifications/bundle_identifier/NOTIFICATION_GROUPING_APP_ID"),
            SettingsURLEntry(name: "Customize Notifications", fullPath: "Notifications > [bundle identifier] > Customize Notifications", url: "settings-navigation://com.apple.Settings.Notifications/bundle_identifier/custom"),
        ]),
        SettingsURLCategory(name: "Sounds & Haptics", icon: "speaker.wave.3", entries: [
            SettingsURLEntry(name: "Sounds & Haptics", fullPath: "Sounds & Haptics", url: "settings-navigation://com.apple.Settings.Sounds"),
            SettingsURLEntry(name: "Microphone", fullPath: "Sounds & Haptics > Microphone (button)", url: "settings-navigation://com.apple.Settings.Sounds#MICROPHONE"),
            SettingsURLEntry(name: "Change with Buttons", fullPath: "Sounds & Haptics > Change with Buttons (switch)", url: "settings-navigation://com.apple.Settings.Sounds#CHANGE_WITH_BUTTONS"),
            SettingsURLEntry(name: "Haptics", fullPath: "Sounds & Haptics > Haptics (button)", url: "settings-navigation://com.apple.Settings.Sounds#HAPTICS"),
            SettingsURLEntry(name: "Ringtone", fullPath: "Sounds & Haptics > Ringtone", url: "settings-navigation://com.apple.Settings.Sounds/Ringtone"),
            SettingsURLEntry(name: "Text Tone", fullPath: "Sounds & Haptics > Text Tone", url: "settings-navigation://com.apple.Settings.Sounds/Text_Messages"),
            SettingsURLEntry(name: "New Voicemail", fullPath: "Sounds & Haptics > New Voicemail", url: "settings-navigation://com.apple.Settings.Sounds/Voicemail"),
            SettingsURLEntry(name: "New Mail", fullPath: "Sounds & Haptics > New Mail (button)", url: "settings-navigation://com.apple.Settings.Sounds#NEW_MAIL"),
            SettingsURLEntry(name: "Sent Mail", fullPath: "Sounds & Haptics > Sent Mail", url: "settings-navigation://com.apple.Settings.Sounds/SENT_MAIL"),
            SettingsURLEntry(name: "Celendar Alerts", fullPath: "Sounds & Haptics > Celendar Alerts", url: "settings-navigation://com.apple.Settings.Sounds/Calendar%20Alarm"),
            SettingsURLEntry(name: "Reminder Alerts", fullPath: "Sounds & Haptics > Reminder Alerts", url: "settings-navigation://com.apple.Settings.Sounds/Reminder%20Alerts"),
            SettingsURLEntry(name: "Default Alerts", fullPath: "Sounds & Haptics > Default Alerts", url: "settings-navigation://com.apple.Settings.Sounds/DEFAULT_ALERTS"),
            SettingsURLEntry(name: "Keyboard Feedback", fullPath: "Sounds & Haptics > Keyboard Feedback", url: "settings-navigation://com.apple.Settings.Sounds/KEYBOARD_FEEDBACK"),
            SettingsURLEntry(name: "Lock Sound", fullPath: "Sounds & Haptics > Lock Sound", url: "settings-navigation://com.apple.Settings.Sounds#LOCK_SOUND_SWITCH"),
            SettingsURLEntry(name: "Volume Limit", fullPath: "Sounds & Haptics > Built-In Speaker > Volume Limit", url: "settings-navigation://com.apple.Settings.Sounds/VOLUME_LIMIT"),
            SettingsURLEntry(name: "Reduce Loud Sounds", fullPath: "Sounds & Haptics > Reduce Loud Sounds", url: "settings-navigation://com.apple.Settings.Sounds#LATE_NIGHT_MODE_SWITCH"),
            SettingsURLEntry(name: "Headphone Safety", fullPath: "Sounds & Haptics > Headphone Safety", url: "settings-navigation://com.apple.Settings.Sounds/HEADPHONE_LEVEL_LIMIT_SETTING"),
            SettingsURLEntry(name: "Personalized Spatial Audio", fullPath: "Sounds & Haptics > Personalized Spatial Audio", url: "settings-navigation://com.apple.Settings.Sounds/PERSONALIZED_SPATIAL_AUDIO"),
        ]),
        SettingsURLCategory(name: "Focus", icon: "moon", entries: [
            SettingsURLEntry(name: "Focus", fullPath: "Focus", url: "settings-navigation://com.apple.Settings.Focus"),
            SettingsURLEntry(name: "Share Across Devices", fullPath: "Focus > Share Across Devices (switch)", url: "settings-navigation://com.apple.Settings.Focus#Share%20Across%20Devices"),
            SettingsURLEntry(name: "Focus Status", fullPath: "Focus > Focus Status", url: "settings-navigation://com.apple.Settings.Focus/Focus%20Status"),
        ]),
        SettingsURLCategory(name: "Screen Time", icon: "hourglass", entries: [
            SettingsURLEntry(name: "Screen Time", fullPath: "Screen Time", url: "settings-navigation://com.apple.Settings.ScreenTime"),
            SettingsURLEntry(name: "See All App & Website Activity If App & Website Activity is enabled", fullPath: "Screen Time > See All App & Website Activity If App & Website Activity is enabled", url: "settings-navigation://com.apple.Settings.ScreenTime/SCREEN_TIME_SUMMARY"),
            SettingsURLEntry(name: "See All App & Website Activity – Week (tab) If App & Website Activity is enabled", fullPath: "Screen Time > See All App & Website Activity – Week (tab) If App & Website Activity is enabled", url: "settings-navigation://com.apple.Settings.ScreenTime/SCREEN_TIME_SUMMARY/WEEK"),
            SettingsURLEntry(name: "See All App & Website Activity – Day (tab) If App & Website Activity is enabled", fullPath: "Screen Time > See All App & Website Activity – Day (tab) If App & Website Activity is enabled", url: "settings-navigation://com.apple.Settings.ScreenTime/SCREEN_TIME_SUMMARY/DAY"),
            SettingsURLEntry(name: "See All App & Website Activity – Most Used (section) If App & Website Activity is enabled", fullPath: "Screen Time > See All App & Website Activity – Most Used (section) If App & Website Activity is enabled", url: "settings-navigation://com.apple.Settings.ScreenTime/SCREEN_TIME_SUMMARY/Most%20Used"),
            SettingsURLEntry(name: "See All App & Website Activity – Pickups (section) If App & Website Activity is enabled", fullPath: "Screen Time > See All App & Website Activity – Pickups (section) If App & Website Activity is enabled", url: "settings-navigation://com.apple.Settings.ScreenTime/SCREEN_TIME_SUMMARY/Pickups"),
            SettingsURLEntry(name: "See All App & Website Activity – Notifications (section) If App & Website Activity is enabled", fullPath: "Screen Time > See All App & Website Activity – Notifications (section) If App & Website Activity is enabled", url: "settings-navigation://com.apple.Settings.ScreenTime/SCREEN_TIME_SUMMARY/Notifications"),
            SettingsURLEntry(name: "[bundle identifier] If App & Website Activity is enabled", fullPath: "Screen Time > See All App & Website Activity – Notifications > [bundle identifier] If App & Website Activity is enabled", url: "settings-navigation://com.apple.Settings.ScreenTime/SCREEN_TIME_SUMMARY/bundle_identifier"),
            SettingsURLEntry(name: "Downtime If App & Website Activity is enabled", fullPath: "Screen Time > Downtime If App & Website Activity is enabled", url: "settings-navigation://com.apple.Settings.ScreenTime/DOWNTIME"),
            SettingsURLEntry(name: "App Limits If App & Website Activity is enabled", fullPath: "Screen Time > App Limits If App & Website Activity is enabled", url: "settings-navigation://com.apple.Settings.ScreenTime/APP_LIMITS"),
            SettingsURLEntry(name: "Always Allowed If App & Website Activity is enabled", fullPath: "Screen Time > Always Allowed If App & Website Activity is enabled", url: "settings-navigation://com.apple.Settings.ScreenTime/ALWAYS_ALLOWED"),
            SettingsURLEntry(name: "Screen Distance", fullPath: "Screen Time > Screen Distance", url: "settings-navigation://com.apple.Settings.ScreenTime/EYE_DISTANCE"),
            SettingsURLEntry(name: "Screen Distance", fullPath: "Screen Time > Screen Distance > Screen Distance (switch)", url: "settings-navigation://com.apple.Settings.ScreenTime/EYE_DISTANCE/Screen%20Distance"),
            SettingsURLEntry(name: "Communication Limits", fullPath: "Screen Time > Communication Limits", url: "settings-navigation://com.apple.Settings.ScreenTime/COMMUNICATION_LIMITS"),
            SettingsURLEntry(name: "During Screen Time", fullPath: "Screen Time > Communication Limits > During Screen Time", url: "settings-navigation://com.apple.Settings.ScreenTime/COMMUNICATION_LIMITS/During%20Screen%20Time"),
            SettingsURLEntry(name: "During Downtime", fullPath: "Screen Time > Communication Limits > During Downtime", url: "settings-navigation://com.apple.Settings.ScreenTime/COMMUNICATION_LIMITS/During%20Downtime"),
            SettingsURLEntry(name: "Communication Safety", fullPath: "Screen Time > Communication Safety", url: "settings-navigation://com.apple.Settings.ScreenTime/COMMUNICATION_SAFETY"),
            SettingsURLEntry(name: "Communication Safety", fullPath: "Screen Time > Communication Safety > Communication Safety (switch)", url: "settings-navigation://com.apple.Settings.ScreenTime/COMMUNICATION_SAFETY/Communication%20Safety"),
            SettingsURLEntry(name: "View Child Safety Resources", fullPath: "Screen Time > Communication Safety > View Child Safety Resources", url: "settings-navigation://com.apple.Settings.ScreenTime/COMMUNICATION_SAFETY/View%20Child%20Safety%20Resources"),
            SettingsURLEntry(name: "Improve Communication Safety", fullPath: "Screen Time > Communication Safety > Improve Communication Safety (switch)", url: "settings-navigation://com.apple.Settings.ScreenTime/COMMUNICATION_SAFETY/Improve%20Communication%20Safety"),
            SettingsURLEntry(name: "Content & Privacy Restrictions", fullPath: "Screen Time > Content & Privacy Restrictions", url: "settings-navigation://com.apple.Settings.ScreenTime/CONTENT_PRIVACY"),
            SettingsURLEntry(name: "View Profiles", fullPath: "Screen Time > Content & Privacy Restrictions > View Profiles", url: "settings-navigation://com.apple.Settings.ScreenTime/CONTENT_PRIVACY/View%20Profiles"),
            SettingsURLEntry(name: "Content & Privacy Restrictions", fullPath: "Screen Time > Content & Privacy Restrictions > Content & Privacy Restrictions (switch)", url: "settings-navigation://com.apple.Settings.ScreenTime/CONTENT_PRIVACY/Content%20%26%20Privacy%20Restrictions"),
            SettingsURLEntry(name: "iTunes & App Store Purchases", fullPath: "Screen Time > Content & Privacy Restrictions > iTunes & App Store Purchases", url: "settings-navigation://com.apple.Settings.ScreenTime/CONTENT_PRIVACY/PURCHASES"),
            SettingsURLEntry(name: "Allowed Apps & Features", fullPath: "Screen Time > Content & Privacy Restrictions > Allowed Apps & Features", url: "settings-navigation://com.apple.Settings.ScreenTime/CONTENT_PRIVACY/ALLOWED_APPS"),
            SettingsURLEntry(name: "App Store, Media, Web, & Games", fullPath: "Screen Time > Content & Privacy Restrictions > App Store, Media, Web, & Games", url: "settings-navigation://com.apple.Settings.ScreenTime/CONTENT_PRIVACY/CONTENT_RESTRICTIONS"),
            SettingsURLEntry(name: "Intelligence & Siri", fullPath: "Screen Time > Content & Privacy Restrictions > Intelligence & Siri", url: "settings-navigation://com.apple.Settings.ScreenTime/CONTENT_PRIVACY/SIRI_AND_INTELLIGENCE_RESTRICTIONS"),
            SettingsURLEntry(name: "Location Services", fullPath: "Screen Time > Content & Privacy Restrictions > Location Services", url: "settings-navigation://com.apple.Settings.ScreenTime/CONTENT_PRIVACY/Location%20Services"),
            SettingsURLEntry(name: "Share My Location", fullPath: "Screen Time > Content & Privacy Restrictions > Share My Location", url: "settings-navigation://com.apple.Settings.ScreenTime/CONTENT_PRIVACY/Share%20My%20Location"),
            SettingsURLEntry(name: "Privacy", fullPath: "Screen Time > Content & Privacy Restrictions > Privacy (section)", url: "settings-navigation://com.apple.Settings.ScreenTime/CONTENT_PRIVACY/Privacy"),
            SettingsURLEntry(name: "Allow Changes to Passcode & Face ID", fullPath: "Screen Time > Content & Privacy Restrictions > Allow Changes to Passcode & Face ID", url: "settings-navigation://com.apple.Settings.ScreenTime/CONTENT_PRIVACY/Passcode%20%26%20Face%20ID"),
            SettingsURLEntry(name: "Allow Changes to Accounts", fullPath: "Screen Time > Content & Privacy Restrictions > Allow Changes to Accounts", url: "settings-navigation://com.apple.Settings.ScreenTime/CONTENT_PRIVACY/Accounts"),
            SettingsURLEntry(name: "Allow Changes to Cellular Data", fullPath: "Screen Time > Content & Privacy Restrictions > Allow Changes to Cellular Data", url: "settings-navigation://com.apple.Settings.ScreenTime/CONTENT_PRIVACY/Cellular%20Data"),
            SettingsURLEntry(name: "Allow Changes to Reduce Loud Audio", fullPath: "Screen Time > Content & Privacy Restrictions > Allow Changes to Reduce Loud Audio", url: "settings-navigation://com.apple.Settings.ScreenTime/CONTENT_PRIVACY/Reduce%20Loud%20Audio"),
            SettingsURLEntry(name: "Allow Changes to Speaker Volume Limit", fullPath: "Screen Time > Content & Privacy Restrictions > Allow Changes to Speaker Volume Limit", url: "settings-navigation://com.apple.Settings.ScreenTime/CONTENT_PRIVACY/Speaker%20Volume%20Limit"),
            SettingsURLEntry(name: "Allow Changes to Driving Focus", fullPath: "Screen Time > Content & Privacy Restrictions > Allow Changes to Driving Focus", url: "settings-navigation://com.apple.Settings.ScreenTime/CONTENT_PRIVACY/Driving%20Focus"),
            SettingsURLEntry(name: "Allow Changes to TV Provider", fullPath: "Screen Time > Content & Privacy Restrictions > Allow Changes to TV Provider", url: "settings-navigation://com.apple.Settings.ScreenTime/CONTENT_PRIVACY/TV%20Provider"),
            SettingsURLEntry(name: "Allow Changes to Background App Activity", fullPath: "Screen Time > Content & Privacy Restrictions > Allow Changes to Background App Activity", url: "settings-navigation://com.apple.Settings.ScreenTime/CONTENT_PRIVACY/Background%20App%20Activity"),
            SettingsURLEntry(name: "Lock Screen Time Settings", fullPath: "Screen Time > Lock Screen Time Settings (button)", url: "settings-navigation://com.apple.Settings.ScreenTime#Lock%20Screen%20Time%20Settings"),
            SettingsURLEntry(name: "Share Across Devices", fullPath: "Screen Time > Share Across Devices (switch)", url: "settings-navigation://com.apple.Settings.ScreenTime#Share%20Across%20Devices"),
        ]),
        SettingsURLCategory(name: "Touch ID & Passcode", icon: "lock", entries: [
            SettingsURLEntry(name: "Touch ID & Passcode", fullPath: "Touch ID & Passcode", url: "settings-navigation://com.apple.Settings.Passcode"),
            SettingsURLEntry(name: "Change Passcode", fullPath: "Touch ID & Passcode > Change Passcode (button)", url: "settings-navigation://com.apple.Settings.Passcode#CHANGE_PASSCODE"),
            SettingsURLEntry(name: "Require Passcode", fullPath: "Touch ID & Passcode > Require Passcode", url: "settings-navigation://com.apple.Settings.Passcode/PASSCODE_REQ"),
            SettingsURLEntry(name: "Erase Data", fullPath: "Touch ID & Passcode > Erase Data (switch)", url: "settings-navigation://com.apple.Settings.Passcode#WIPE_DEVICE"),
        ]),
        SettingsURLCategory(name: "Emergency SOS", icon: "sos", entries: [
            SettingsURLEntry(name: "Emergency SOS", fullPath: "Emergency SOS", url: "settings-navigation://com.apple.Settings.SOS"),
            SettingsURLEntry(name: "Call with Hold and Release", fullPath: "Emergency SOS > Call with Hold and Release (switch)", url: "settings-navigation://com.apple.Settings.SOS#CALL_WITH_HOLD"),
            SettingsURLEntry(name: "Call with 5 Button Presses", fullPath: "Emergency SOS > Call with 5 Button Presses (switch)", url: "settings-navigation://com.apple.Settings.SOS#CALL_WITH_PRESSES"),
            SettingsURLEntry(name: "Set up Emergency Contacts in Health", fullPath: "Emergency SOS > Set up Emergency Contacts in Health (button)", url: "settings-navigation://com.apple.Settings.SOS#OPEN_HEALTH"),
        ]),
        SettingsURLCategory(name: "Privacy & Security", icon: "hand.raised", entries: [
            SettingsURLEntry(name: "Privacy & Security", fullPath: "Privacy & Security", url: "settings-navigation://com.apple.Settings.PrivacyAndSecurity"),
            SettingsURLEntry(name: "Location Services", fullPath: "Privacy & Security > Location Services", url: "settings-navigation://com.apple.Settings.PrivacyAndSecurity/LOCATION"),
            SettingsURLEntry(name: "Location Alerts", fullPath: "Privacy & Security > Location Services > Location Alerts", url: "settings-navigation://com.apple.Settings.PrivacyAndSecurity/LOCATION/LOCATION_SERVICES_MASTER"),
            SettingsURLEntry(name: "Share My Location", fullPath: "Privacy & Security > Location Services > Share My Location", url: "settings-navigation://com.apple.Settings.PrivacyAndSecurity/LOCATION/LOCATION_SHARING"),
            SettingsURLEntry(name: "App Clips", fullPath: "Privacy & Security > Location Services > App Clips", url: "settings-navigation://com.apple.Settings.PrivacyAndSecurity/LOCATION/APP_CLIPS"),
            SettingsURLEntry(name: "[bundle identifier]", fullPath: "Privacy & Security > Location Services > [bundle identifier]", url: "settings-navigation://com.apple.Settings.PrivacyAndSecurity/LOCATION/bundle_identifier"),
            SettingsURLEntry(name: "System Services", fullPath: "Privacy & Security > Location Services > System Services", url: "settings-navigation://com.apple.Settings.PrivacyAndSecurity/LOCATION/SYSTEM_SERVICES"),
            SettingsURLEntry(name: "Tracking", fullPath: "Privacy & Security > Tracking", url: "settings-navigation://com.apple.Settings.PrivacyAndSecurity/USER_TRACKING"),
            SettingsURLEntry(name: "Calendars", fullPath: "Privacy & Security > Calendars", url: "settings-navigation://com.apple.Settings.PrivacyAndSecurity/CALENDARS"),
            SettingsURLEntry(name: "Contacts", fullPath: "Privacy & Security > Contacts", url: "settings-navigation://com.apple.Settings.PrivacyAndSecurity/CONTACTS"),
            SettingsURLEntry(name: "Files & Folders", fullPath: "Privacy & Security > Files & Folders", url: "settings-navigation://com.apple.Settings.PrivacyAndSecurity/FILEACCEESS"),
            SettingsURLEntry(name: "Health Data", fullPath: "Privacy & Security > Health Data", url: "settings-navigation://com.apple.Settings.PrivacyAndSecurity/HEALTH_DATA"),
            SettingsURLEntry(name: "Home Accessories", fullPath: "Privacy & Security > Home Accessories", url: "settings-navigation://com.apple.Settings.PrivacyAndSecurity/WILLOW"),
            SettingsURLEntry(name: "Media & Apple Music", fullPath: "Privacy & Security > Media & Apple Music", url: "settings-navigation://com.apple.Settings.PrivacyAndSecurity/MEDIALIBRARY"),
            SettingsURLEntry(name: "Passkeys Access for Web Browsers", fullPath: "Privacy & Security > Passkeys Access for Web Browsers", url: "settings-navigation://com.apple.Settings.PrivacyAndSecurity/PASSKEYS"),
            SettingsURLEntry(name: "Photos", fullPath: "Privacy & Security > Photos", url: "settings-navigation://com.apple.Settings.PrivacyAndSecurity/PHOTOS"),
            SettingsURLEntry(name: "Reminders", fullPath: "Privacy & Security > Reminders", url: "settings-navigation://com.apple.Settings.PrivacyAndSecurity/REMINDERS"),
            SettingsURLEntry(name: "Wallet", fullPath: "Privacy & Security > Wallet", url: "settings-navigation://com.apple.Settings.PrivacyAndSecurity/WALLET"),
            SettingsURLEntry(name: "Accessories", fullPath: "Privacy & Security > Accessories", url: "settings-navigation://com.apple.Settings.PrivacyAndSecurity/ACCESSORY_SETUP"),
            SettingsURLEntry(name: "Bluetooth", fullPath: "Privacy & Security > Bluetooth", url: "settings-navigation://com.apple.Settings.PrivacyAndSecurity/BT_PERIPHERAL"),
            SettingsURLEntry(name: "Camera", fullPath: "Privacy & Security > Camera", url: "settings-navigation://com.apple.Settings.PrivacyAndSecurity/CAMERA"),
            SettingsURLEntry(name: "Contactless & NFC", fullPath: "Privacy & Security > Contactless & NFC", url: "settings-navigation://com.apple.Settings.PrivacyAndSecurity/CONTACTLESS_NFC"),
            SettingsURLEntry(name: "Critical Messages", fullPath: "Privacy & Security > Critical Messages", url: "settings-navigation://com.apple.Settings.PrivacyAndSecurity/CRITICAL_MESSAGES"),
            SettingsURLEntry(name: "Local Network", fullPath: "Privacy & Security > Local Network", url: "settings-navigation://com.apple.Settings.PrivacyAndSecurity/LOCAL_NETWORK"),
            SettingsURLEntry(name: "Microphone", fullPath: "Privacy & Security > Microphone", url: "settings-navigation://com.apple.Settings.PrivacyAndSecurity/MICROPHONE"),
            SettingsURLEntry(name: "Motion & Fitness", fullPath: "Privacy & Security > Motion & Fitness", url: "settings-navigation://com.apple.Settings.PrivacyAndSecurity/MOTION"),
            SettingsURLEntry(name: "Nearby Interactions", fullPath: "Privacy & Security > Nearby Interactions", url: "settings-navigation://com.apple.Settings.PrivacyAndSecurity/NEARBY_INTERACTIONS"),
            SettingsURLEntry(name: "Paired Devices", fullPath: "Privacy & Security > Paired Devices", url: "settings-navigation://com.apple.Settings.PrivacyAndSecurity/PAIRED_DEVICES"),
            SettingsURLEntry(name: "Research Sensor & Usage Data", fullPath: "Privacy & Security > Research Sensor & Usage Data", url: "settings-navigation://com.apple.Settings.PrivacyAndSecurity/ALMANAC"),
            SettingsURLEntry(name: "Speech Recognition", fullPath: "Privacy & Security > Speech Recognition", url: "settings-navigation://com.apple.Settings.PrivacyAndSecurity/SPEECH_RECOGNITION"),
            SettingsURLEntry(name: "Journaling Suggestions", fullPath: "Privacy & Security > Journaling Suggestions", url: "settings-navigation://com.apple.Settings.PrivacyAndSecurity/JOURNALING_SUGGESTIONS"),
            SettingsURLEntry(name: "Blocked Contacts", fullPath: "Privacy & Security > Blocked Contacts", url: "settings-navigation://com.apple.Settings.PrivacyAndSecurity/BLOCKLIST"),
            SettingsURLEntry(name: "Safety Check", fullPath: "Privacy & Security > Safety Check", url: "settings-navigation://com.apple.Settings.PrivacyAndSecurity/SAFETY_CHECK"),
            SettingsURLEntry(name: "Sensitive Content Warning", fullPath: "Privacy & Security > Sensitive Content Warning", url: "settings-navigation://com.apple.Settings.PrivacyAndSecurity/NUDITY_DETECTION"),
            SettingsURLEntry(name: "Analytics & Improvements", fullPath: "Privacy & Security > Analytics & Improvements", url: "settings-navigation://com.apple.Settings.PrivacyAndSecurity/PROBLEM_REPORTING"),
            SettingsURLEntry(name: "Apple Advertising", fullPath: "Privacy & Security > Apple Advertising", url: "settings-navigation://com.apple.Settings.PrivacyAndSecurity/ADVERTISING"),
            SettingsURLEntry(name: "App Privacy Report", fullPath: "Privacy & Security > App Privacy Report", url: "settings-navigation://com.apple.Settings.PrivacyAndSecurity/PRIVACY_REPORT"),
            SettingsURLEntry(name: "Background Security Improvements", fullPath: "Privacy & Security > Background Security Improvements", url: "settings-navigation://com.apple.Settings.PrivacyAndSecurity/BACKGROUND_SECURITY_IMPROVEMENTS"),
            SettingsURLEntry(name: "Stolen Device Protection", fullPath: "Privacy & Security > Stolen Device Protection", url: "settings-navigation://com.apple.Settings.PrivacyAndSecurity/STOLEN_DEVICE_PROTECTION"),
            SettingsURLEntry(name: "Lockdown Mode", fullPath: "Privacy & Security > Lockdown Mode", url: "settings-navigation://com.apple.Settings.PrivacyAndSecurity/LOCKDOWN_MODE"),
        ]),
        SettingsURLCategory(name: "Game Center", icon: "gamecontroller", entries: [
            SettingsURLEntry(name: "Game Center", fullPath: "Game Center", url: "settings-navigation://com.apple.Settings.GameCenter"),
            SettingsURLEntry(name: "Customize Profile", fullPath: "Game Center > Customize Profile", url: "settings-navigation://com.apple.Settings.GameCenter/EDIT_PROFILE"),
            SettingsURLEntry(name: "All Friends", fullPath: "Game Center > All Friends", url: "settings-navigation://com.apple.Settings.GameCenter/ALL_FRIENDS"),
            SettingsURLEntry(name: "Friends Requests", fullPath: "Game Center > Friends Requests", url: "settings-navigation://com.apple.Settings.GameCenter/FRIEND_REQUESTS"),
            SettingsURLEntry(name: "Invite Friends", fullPath: "Game Center > Invite Friends", url: "settings-navigation://com.apple.Settings.GameCenter/INVITE_FRIENDS"),
        ]),
        SettingsURLCategory(name: "iCloud", icon: "icloud", entries: [
            SettingsURLEntry(name: "iCloud", fullPath: "iCloud", url: "settings-navigation://com.apple.Settings.iCloud"),
            SettingsURLEntry(name: "Storage", fullPath: "iCloud > Storage", url: "settings-navigation://com.apple.Settings.iCloud/STORAGE_AND_BACKUP"),
            SettingsURLEntry(name: "Change Storage Plan", fullPath: "iCloud > Storage > Change Storage Plan", url: "settings-navigation://com.apple.Settings.iCloud/STORAGE_AND_BACKUP/CHANGE_STORAGE_PLAN"),
            SettingsURLEntry(name: "Saved to iCloud", fullPath: "iCloud > Saved to iCloud", url: "settings-navigation://com.apple.Settings.iCloud/com.apple.Dataclass"),
            SettingsURLEntry(name: "iCloud Photos", fullPath: "iCloud > Saved to iCloud > iCloud Photos", url: "settings-navigation://com.apple.Settings.iCloud/com.apple.Dataclass.CloudPhotos"),
            SettingsURLEntry(name: "iCloud Drive", fullPath: "iCloud > Saved to iCloud > iCloud Drive", url: "settings-navigation://com.apple.Settings.iCloud/com.apple.Dataclass.Ubiquity"),
            SettingsURLEntry(name: "iCloud Mail", fullPath: "iCloud > Saved to iCloud > iCloud Mail", url: "settings-navigation://com.apple.Settings.iCloud/com.apple.Dataclass.Mail"),
            SettingsURLEntry(name: "Addresses", fullPath: "iCloud > Saved to iCloud > iCloud Mail > Addresses", url: "settings-navigation://com.apple.Settings.iCloud/com.apple.Dataclass.Mail/ALIASES"),
            SettingsURLEntry(name: "iCloud Mail Cleanup", fullPath: "iCloud > Saved to iCloud > iCloud Mail > iCloud Mail Cleanup", url: "settings-navigation://com.apple.Settings.iCloud/com.apple.Dataclass.Mail/ICLOUD_MAIL_CLEANUP"),
            SettingsURLEntry(name: "iCloud Mail Rules", fullPath: "iCloud > Saved to iCloud > iCloud Mail > iCloud Mail Rules", url: "settings-navigation://com.apple.Settings.iCloud/com.apple.Dataclass.Mail/SERVER_SIDE_RULES"),
            SettingsURLEntry(name: "Auto-Reply", fullPath: "iCloud > Saved to iCloud > iCloud Mail > Auto-Reply", url: "settings-navigation://com.apple.Settings.iCloud/com.apple.Dataclass.Mail/AUTO_REPLY"),
            SettingsURLEntry(name: "Mail Forwarding some delay", fullPath: "iCloud > Saved to iCloud > iCloud Mail > Mail Forwarding some delay", url: "settings-navigation://com.apple.Settings.iCloud/com.apple.Dataclass.Mail/MAIL_FORWARDING"),
            SettingsURLEntry(name: "Mailbox Behaviors", fullPath: "iCloud > Saved to iCloud > iCloud Mail > Mailbox Behaviors", url: "settings-navigation://com.apple.Settings.iCloud/com.apple.Dataclass.Mail/MAILBOX_BEHAVIORS"),
            SettingsURLEntry(name: "Import Messages", fullPath: "iCloud > Saved to iCloud > iCloud Mail > Import Messages", url: "settings-navigation://com.apple.Settings.iCloud/com.apple.Dataclass.Mail/MAIL_IMPORT"),
            SettingsURLEntry(name: "Signing and Encryption", fullPath: "iCloud > Saved to iCloud > iCloud Mail > Signing and Encryption", url: "settings-navigation://com.apple.Settings.iCloud/com.apple.Dataclass.Mail/END_TO_END_ENCRYPTION"),
            SettingsURLEntry(name: "Custom Email Domain some delay", fullPath: "iCloud > Saved to iCloud > iCloud Mail > Custom Email Domain some delay", url: "settings-navigation://com.apple.Settings.iCloud/com.apple.Dataclass.Mail/BYOD_SETTING_SPECIFIER_ID"),
            SettingsURLEntry(name: "Passwords & Keychan", fullPath: "iCloud > Saved to iCloud > Passwords & Keychan", url: "settings-navigation://com.apple.Settings.iCloud/com.apple.Dataclass.KeychainSync"),
            SettingsURLEntry(name: "Notes", fullPath: "iCloud > Saved to iCloud > Notes", url: "settings-navigation://com.apple.Settings.iCloud/com.apple.Dataclass.Notes"),
            SettingsURLEntry(name: "Messages in iCloud", fullPath: "iCloud > Saved to iCloud > Messages in iCloud", url: "settings-navigation://com.apple.Settings.iCloud/com.apple.Dataclass.Messages"),
            SettingsURLEntry(name: "Health", fullPath: "iCloud > Saved to iCloud > Health", url: "settings-navigation://com.apple.Settings.iCloud/com.apple.Dataclass.Health"),
            SettingsURLEntry(name: "iCloud Calendar", fullPath: "iCloud > Saved to iCloud > iCloud Calendar", url: "settings-navigation://com.apple.Settings.iCloud/com.apple.Dataclass.Calendars"),
            SettingsURLEntry(name: "Backup", fullPath: "iCloud > Backup", url: "settings-navigation://com.apple.Settings.iCloud/BACKUP"),
            SettingsURLEntry(name: "Backup Details", fullPath: "iCloud > Backup > All Device Backups > [current device] > Backup Details", url: "settings-navigation://com.apple.Settings.iCloud/STORAGE_AND_BACKUP/CURRENT_DEVICE_BACKUP"),
            SettingsURLEntry(name: "Private Relay", fullPath: "iCloud > Private Relay", url: "settings-navigation://com.apple.Settings.iCloud/INTERNET_PRIVACY"),
            SettingsURLEntry(name: "Hide My Email some delay", fullPath: "iCloud > Hide My Email some delay", url: "settings-navigation://com.apple.Settings.iCloud/PRIVATE_EMAIL_MANAGE"),
            SettingsURLEntry(name: "Advanced Data Protection", fullPath: "iCloud > Advanced Data Protection", url: "settings-navigation://com.apple.Settings.iCloud/ICLOUD_ADP_SPECIFIER_NAME"),
        ]),
        SettingsURLCategory(name: "Wallet & Apple Pay", icon: "wallet.pass", entries: [
            SettingsURLEntry(name: "Wallet & Apple Pay", fullPath: "Wallet & Apple Pay", url: "settings-navigation://com.apple.Settings.Wallet"),
            SettingsURLEntry(name: "Apple Pay Defaults", fullPath: "Wallet & Apple Pay > Apple Pay Defaults", url: "settings-navigation://com.apple.Settings.Wallet/applePayDefaults"),
        ]),
        SettingsURLCategory(name: "Apps", icon: "square.grid.2x2", entries: [
            SettingsURLEntry(name: "Apps", fullPath: "Apps", url: "settings-navigation://com.apple.Settings.Apps"),
            SettingsURLEntry(name: "Default Apps", fullPath: "Apps > Default Apps", url: "settings-navigation://com.apple.Settings.Apps/com.apple.Settings.Apps.DefaultApps"),
            SettingsURLEntry(name: "[bundle identifier]", fullPath: "Apps > [bundle identifier]", url: "settings-navigation://com.apple.Settings.Apps/bundle_identifier"),
            SettingsURLEntry(name: "AirPort Utility", fullPath: "Apps > AirPort Utility", url: "settings-navigation://com.apple.Settings.Apps/com.apple.airport.mobileairportutility"),
            SettingsURLEntry(name: "App Store", fullPath: "Apps > App Store", url: "settings-navigation://com.apple.Settings.Apps/com.apple.AppStore"),
            SettingsURLEntry(name: "Apple Store", fullPath: "Apps > Apple Store", url: "settings-navigation://com.apple.Settings.Apps/com.apple.store.Jolly"),
            SettingsURLEntry(name: "Books", fullPath: "Apps > Books", url: "settings-navigation://com.apple.Settings.Apps/com.apple.iBooks"),
            SettingsURLEntry(name: "Calculator", fullPath: "Apps > Calculator", url: "settings-navigation://com.apple.Settings.Apps/com.apple.calculator"),
            SettingsURLEntry(name: "Calendar", fullPath: "Apps > Calendar", url: "settings-navigation://com.apple.Settings.Apps/com.apple.mobilecal"),
            SettingsURLEntry(name: "Classical", fullPath: "Apps > Classical", url: "settings-navigation://com.apple.Settings.Apps/com.apple.music.classical"),
            SettingsURLEntry(name: "Clock", fullPath: "Apps > Clock", url: "settings-navigation://com.apple.Settings.Apps/com.apple.mobiletimer"),
            SettingsURLEntry(name: "Compass", fullPath: "Apps > Compass", url: "settings-navigation://com.apple.Settings.Apps/com.apple.compass"),
            SettingsURLEntry(name: "Configurator", fullPath: "Apps > Configurator", url: "settings-navigation://com.apple.Settings.Apps/com.apple.ios.configurator"),
            SettingsURLEntry(name: "Contacts", fullPath: "Apps > Contacts", url: "settings-navigation://com.apple.Settings.Apps/com.apple.MobileAddressBook"),
            SettingsURLEntry(name: "FaceTime", fullPath: "Apps > FaceTime", url: "settings-navigation://com.apple.Settings.Apps/com.apple.facetime"),
            SettingsURLEntry(name: "Files", fullPath: "Apps > Files", url: "settings-navigation://com.apple.Settings.Apps/com.apple.DocumentsApp"),
            SettingsURLEntry(name: "Final Cut Camera", fullPath: "Apps > Final Cut Camera", url: "settings-navigation://com.apple.Settings.Apps/com.apple.FinalCutApp.companion"),
            SettingsURLEntry(name: "Freeform", fullPath: "Apps > Freeform", url: "settings-navigation://com.apple.Settings.Apps/com.apple.freeform"),
            SettingsURLEntry(name: "Games", fullPath: "Apps > Games", url: "settings-navigation://com.apple.Settings.Apps/com.apple.games"),
            SettingsURLEntry(name: "GarageBand", fullPath: "Apps > GarageBand", url: "settings-navigation://com.apple.Settings.Apps/com.apple.mobilegarageband"),
        ]),
    ]
}
